/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Collaborator: typeof import('./src/components/Collaborator.vue')['default']
    Contact: typeof import('./src/components/Contact.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Footer2: typeof import('./src/components/Footer2.vue')['default']
    HeaderTab: typeof import('./src/components/HeaderTab.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    LocaleLanguage: typeof import('./src/components/LocaleLanguage.vue')['default']
    Logos: typeof import('./src/components/Logos.vue')['default']
    Logos1: typeof import('./src/components/Logos1.vue')['default']
    Logos2: typeof import('./src/components/Logos2.vue')['default']
    Logos3: typeof import('./src/components/Logos3.vue')['default']
    Logos4: typeof import('./src/components/Logos4.vue')['default']
    Milestones: typeof import('./src/components/Milestones.vue')['default']
    Products: typeof import('./src/components/Products.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToolBar: typeof import('./src/components/ToolBar.vue')['default']
    TranslationAssistant: typeof import('./src/components/TranslationAssistant.vue')['default']
    VTab: typeof import('./src/components/VTab.vue')['default']
  }
}
